"""empty message

Revision ID: 86fe92fe1fa2
Revises: f1e830b17584
Create Date: 2020-02-13 14:38:14.451719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86fe92fe1fa2'
down_revision = 'f1e830b17584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computer', sa.Column('device_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_computer_device_id'), 'computer', ['device_id'], unique=True)
    op.create_index(op.f('ix_computer_ignore_av_check'), 'computer', ['ignore_av_check'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_computer_ignore_av_check'), table_name='computer')
    op.drop_index(op.f('ix_computer_device_id'), table_name='computer')
    op.drop_column('computer', 'device_id')
    # ### end Alembic commands ###
