"""empty message

Revision ID: f1e830b17584
Revises: 
Create Date: 2019-11-20 15:24:29.044432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e830b17584'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('last_logon_name', sa.String(length=120), nullable=True),
    sa.Column('ignore_av_check', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computer_description'), 'computer', ['description'], unique=False)
    op.create_index(op.f('ix_computer_last_logon_name'), 'computer', ['last_logon_name'], unique=False)
    op.create_index(op.f('ix_computer_name'), 'computer', ['name'], unique=False)
    op.create_index(op.f('ix_computer_source_id'), 'computer', ['source_id'], unique=False)
    source_table = op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(source_table,
                   [
                       {'id': 1, 'name': 'manual'},
                       {'id': 2, 'name': 'external'},
                   ])
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=True)
    op.create_table('mac_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['comp_id'], ['computer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mac_addresses_comp_id'), 'mac_addresses', ['comp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mac_addresses_comp_id'), table_name='mac_addresses')
    op.drop_table('mac_addresses')
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_computer_source_id'), table_name='computer')
    op.drop_index(op.f('ix_computer_name'), table_name='computer')
    op.drop_index(op.f('ix_computer_last_logon_name'), table_name='computer')
    op.drop_index(op.f('ix_computer_description'), table_name='computer')
    op.drop_table('computer')
    # ### end Alembic commands ###
